name: Daily Release Notes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  release-notes:
    runs-on: ubuntu-latest

    env:
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  # optional

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate release notes
        run: python scripts/generate_release_notes.py

      - name: Commit RELEASE_NOTES.md
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add RELEASE_NOTES.md
          git diff --cached --quiet || git commit -m "chore: update release notes [skip ci]"
          git push
