name: Generate Release Notes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC

jobs:
  release_notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install openai requests

      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: your-org/your-repo
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_release_notes.py

      - name: Commit release notes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add RELEASE_NOTES.md
          git diff --cached --quiet || git commit -m "chore: update release notes [skip ci]"
          git push
